name: PC Linux

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  IceSDK:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Install Required Packages
        run: |
          sudo apt update
          sudo apt install -y build-essential git libglfw3-dev libfreetype-dev ccache clang

      - uses: actions/cache@v2
        id: cache
        with:
          path: /tmp/ccache
          key: ${{ runner.os }}-emscripten-${{ hashFiles('**/*.manifest') }}

      - name: Generate Build Files
        run: |
          chmod +x ./tools/linux/gn
          ./tools/linux/gn gen out

      - name: Build IceSDK
        run: |
          export CCACHE_DIR=/tmp/ccache
          chmod +x ./tools/linux/ninja
          ./tools/linux/ninja -C out

      - name: Execute Tests
        run: |
          cd out
          ./TestIceSDK
  